name: Basics

on:
  workflow_dispatch:
  
env:
  name: Heinz
  number: 4711

jobs:
  first-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo Hello env ${{ env.name }}
        
      - run: gh issue create --title "Der Heinz" --body "Thank you for creating a lot of work!"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  second-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo Im running in parallel job
      
  third-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - run: echo Im running in sequential job
